home/urls.py
from django.urls import path

from . import views
#ana urls.py burayı çağırıyor burdanda views.pydeki index fonks çağırıyoruz
urlpatterns = [
    # hiçbir şey olmadığı zaman views deki index git
    path('', views.index, name='index'),
    # ex: /polls/5/
   # path('<int:question_id>/', views.detail, name='detail'),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path("", include("home.urls")),
    path("product/", include("product.urls")),
    path('admin/', admin.site.urls),  # admin şifre merve
    path('user/',  include("user.urls")),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'), #ilki fonsiyon tanımladık ikincisi fonk adını belirtir
    path('referanslar/', views.referanslarimiz, name='referanslarimiz'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_products, name="category_products"),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name="product_detail"),
    path('order/orderproduct/<int:id>', views.orderproduct, name="orderproduct"),
    path('search/', views.product_search, name="product_search"),
    path('search_auto/', views.product_search_auto, name="product_search_auto"),
    path('sss/', views.faq, name='faq')

]


if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #media url ve root görünür olmasını sağlıyor

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Setting, user, comment anasayfayı ilgilendirdiği için burda tanımladık
from django.forms import TextInput, Textarea, ModelForm
from django.utils.safestring import mark_safe

from product.models import Car


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    address = models.CharField(blank=True, max_length=100)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')  # blank true boş bırakabilir sağlıyor
    facebook = models.CharField(blank=True, max_length=50)
    linkedin = models.CharField(blank=True, max_length=50)
    github = models.CharField(blank=True, max_length=50)
    abotus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)  # oluşturulma zmanını tutar
    update_At = models.DateTimeField(auto_now=True)

    def __str__(self):  # adı gözüksün return ettiğinde
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ("New", 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=50)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default="new")
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):  # adı gözüksün return ettiğinde
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']  # bu alanların doldurulmasını istiyoruz
        widgets = {
            'name': TextInput(attrs={'class': 'name-input', 'placeholder': 'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'subject-input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'email-input', 'placeholder': 'Enter Email'}),
            'message': Textarea(attrs={'class': 'textarea', 'placeholder': 'Your message', 'rows': '5'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.IntegerField(blank=True)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    county = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + " " + self.user.last_name + " " + '[' + self.user.username + ']'

    def image_tag(self):  # bu fonskiyonu admin kısmında resimler gözüksün diye yazıyoruz ve bu fonk artık çağıracağız
        return mark_safe('<img src= "{}" height="50"/>'.format(
            self.image.url))  # süslü parantezler içine image url gönderdik. oda admin sayfasında img tag ile gözükmesini sağlar

    image_tag.short_description = 'Image'


class UserProfileFormu(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'county', 'image']


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=10, editable=False)  # üye olmayanlar bu ko ile siparişini takip edecek
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(max_length=20, blank=True)
    date_start = models.CharField(max_length=30)
    date_end = models.CharField(max_length=30)
    quatity =models.CharField(max_length=30)
    car_id = models.IntegerField()
    total =models.CharField(max_length=30)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'city','phone', 'country'] #hangi alanları html de çağıracaksak bunları belirtiyoruz


class Calculate(models.Model):
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    day = models.IntegerField()

    def __str__(self):
        return self.day


class CalculateForm(ModelForm):
    class Meta:
        model = Calculate
        fields = ['date_start', 'date_end'] #hangi alanları html de çağıracaksak bunları belirtiyoruz


class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Car, on_delete=models.CASCADE)
    quatity = models.IntegerField()
    price = models.FloatField()
    date_buy = models.CharField(max_length=8)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.title


class Faq(models.Model):  # sıkça sorulan sorular için model
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernmbr = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)  # oluşturulma zmanını tutar
    update_At = models.DateTimeField(auto_now=True)

    def __str__(self):  # adı gözüksün return ettiğinde
        return self.question

product/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.db import models
from django.forms import ModelForm
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
# Create your models here.
from django.utils.safestring import mark_safe


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)  # id yerine metin ile çağırmak istersek
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children',
                               on_delete=models.CASCADE)  # cascade eğer bu tablo silinirse buna bağlı şeylerde silinsin,self dedğimiz için sadece kendi kendine ilişkisi var
    create_at = models.DateTimeField(auto_now_add=True)  # oluşturulma zmanını tutar
    update_At = models.DateTimeField(auto_now=True)

    def image_tag(self):  # bu fonskiyonu admin kısmında resimler gözüksün diye yazıyoruz ve bu fonk artık çağıracağız
       return mark_safe('<img src= "{}" height="50"/>'.format(self.image.url))  # süslü parantezler içine image url gönderdik. oda admin sayfasında img tag ile gözükmesini sağlar

    def get_absolute_url(self): #otomatik slug oluşturma
        return reverse('category_detail', kwargs={'slug': self.slug})

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self): #alt kategorileri arıyor ve getiriyor
        full_path=[self.title]
        k= self.parent
        while k is not None:
            full_path.append(k.title)
            k= k.parent
        return ' -> '.join(full_path[::-1])


class Car(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)  # category ile ilişkisi var
    title = models.CharField(max_length=150)
    keywords = models.CharField(blank=True, max_length=255)
    description = models.CharField(blank=True, max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')  # images klasörüne kaydet
    price = models.FloatField()
    amount = models.IntegerField()
    slug = models.SlugField(blank=True, max_length=150)
    detail = RichTextUploadingField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_At = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):  # bu fonskiyonu admin kısmında resimler gözüksün diye yazıyoruz ve bu fonk artık çağıracağız
        return mark_safe('<img src= "{}" height="50"/>'.format(
            self.image.url))  # süslü parantezler içine image url gönderdik. oda admin sayfasında img tag ile gözükmesini sağlar

    image_tag.short_description = 'Image'

    def get_absolute_url(self):  # otomatik slug oluşturma
        return reverse('car_detail', kwargs={'slug': self.slug})

class Images(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):  # bu fonskiyonu admin kısmında resimler gözüksün diye yazıyoruz ve bu fonk artık çağıracağız
        return mark_safe('<img src= "{}" height="50"/>'.format(
            self.image.url))  # süslü parantezler içine image url gönderdik. oda admin sayfasında img tag ile gözükmesini sağlar

    image_tag.short_description = 'Image'
class Comment(models.Model):
    STATUS = (
        ('False', 'Hayır'),
        ('New', 'Yeni'),
        ('True', 'Evet'),
    )
    car = models.ForeignKey(Car, on_delete=models.CASCADE)  # category ile ilişkisi var
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length=200)
    rate = models.IntegerField(blank=True)
    status = models.CharField(max_length=10,blank=True, choices=STATUS,default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_At = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields= ['subject','comment' ,'rate'] #hangi alanları html de çağıracaksak bunları belirtiyoruz

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User

from home.models import Calculate


class SearchForm(forms.Form):
    query = forms.CharField(label="Search", max_length=100)
    catid = forms.IntegerField()


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name :')
    email = forms.CharField(max_length=200, label='Email :')
    first_name = forms.CharField(max_length=100, help_text='First Name', label='First Name :')
    last_name = forms.CharField(max_length=100, help_text='Last Name', label='Last Name :')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2',)

class Rezervasyon(forms.Form):
    date_start=forms.DateField()
    date_end = forms.DateField()
    day=forms.IntegerField()
    class Meta:
        model=Calculate
        fields=('date_start','date_end','day')

home/templates/car_search.html
{% extends "homebase.html" %}
{% block title %} {{ product.title }} {% endblock %}
{% block keywords %} {{ product.key }} {% endblock %}
{% block description %} {{ product.description }}{% endblock %}
{% block head %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}"
          xmlns:width="http://www.w3.org/1999/xhtml">
{% endblock %}
{% block body %}
    {% load static %}
    <div style="background-image: url('{% static 'img/page-title.jpg'%}');background-position: center center;
	background-size: cover;padding-top: 20px;">
 <section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>GALERİ</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                        <p>MY RENT A CAR</p>
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
      </div>
    <!--== Page Title Area End ==-->

    <!--== Gallery Page Content Start ==-->
    <section id="gallery-page-content" class="section-padding">
        <div class="container">
        	<div class="row">
        		<div class="col-lg-12">
					<div class="popular-cars-wrap">
						<!-- Filtering Menu -->

						<!-- Filtering Menu -->

						<div class="row popular-car-gird">
							<!-- Single Popular Car Start -->
                            {% for rs in product %}
							<div class="col-lg-4 col-md-6 con suv mpv">
								<div class="single-popular-car">
									<div class="p-car-thumbnails">
										<a class="car-hover" href="/product/{{ rs.id }}/{{ rs.slug }}">
										  <img src="{{ rs.image.url }}" alt="JSOFT">
									   </a>
									</div>

									<div class="p-car-content">
										<h3>
											<a href="/product/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a>
											<span class="price"><i class="fa fa-tag"></i> {{ rs.price }}</span>
										</h3>

										<h5>{{ rs.title }}</h5>

										<div class="p-car-feature">
											<a href="#">2017</a>
											<a href="#">manual</a>
											<a href="#">AIR CONDITION</a>
										</div>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
        			</div>
        		</div>
        	</div>
        </div>
    </section>

{% endblock %}

home/templates/cararea.html
<!--ana sayfada arama kısmı-->
<script>
    $(function () {
        $("#query").autocomplete({
            source: "/search_auto/",
            select: function (event, ui) {//item selected
                AutoCompleteSelectHandler(event, ui)
            },
            minLenght: 2,
        });
    });

    function AutoCompleteSelectHandler(event, ui) {
        var selectObj = ui.item;
    }
</script>
{% load static %}
<div id="book-a-car">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="booka-car-content">
                    <form class="example1" action="/search/" method="post">
                        <div class="pick-date bookinput-itemm">
                            {% csrf_token %}
                            <input class="search-car-inputt" type="text" id="query" name="query" placeholder="Ara..">
                            {% load mptt_tags %}
                        </div>
                        <div class="pick-location bookinput-item">
                            <select name="catid" class="custom-selectt">
                                <option value="0">Tüm Kategoriler</option>
                                {% recursetree category %}
                                    {% if node.is_leaf_node %}
                                        <option value="{{ node.id }}">{{ node.title }}</option>{% endif %}
                                    {% if not node.is_leaf_node %}
                                        <optgroup label="{{ node.title }}">
                                            {{ children }}
                                        </optgroup>
                                    {% endif %}
                                {% endrecursetree %}
                            </select>
                        </div>
                        <div style="margin-left: 24%; width: 150px;height: 40px">
                            <button class="kirala" type="submit">Ara</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

home/templates/choosecar.html
<div class="container" style="margin-top:50px">
    <div class="row">
        <!-- Section Title Start -->
        <div class="col-lg-12">
            <div class="section-title  text-center">
                <h2>ARABANIZI SEÇİN</h2>
                <span class="title-line"><i class="fa fa-car"></i></span>
            </div>
        </div>
        <!-- Section Title End -->
    </div>
    {% load static %}
    <div class="row">
        {% load mptt_tags %}

        <div class="col-lg-2">
            <div class="menu">
                <ul>
                    {% load mptt_tags %}
                    {% recursetree category %}
                        <li>
                            <a href="/category/{{ node.id }}/{{ node.slug }}">
                                {{ node.title }} </a>

                            {% if not node.is_leaf_node %}
                                <ul>
                                    <li>
                                        {{ children }} 
                                    </li>
                                </ul>
                            {% endif %}
                        </li>
                    {% endrecursetree %}
                </ul>
            </div>
        </div>

        <div class="col-lg-9" style="margin-left:70px">
            <h3>SİZİN İÇİN SEÇİLENLER</h3>
            <hr>
            <!-- Choose Cars Content-wrap -->
            <div class="row popular-car-gird">
                {% for rs in randomproducts %}

                    <div class="col-lg-6 col-md-6 con suv mpv">
                        <div class="single-popular-car">
                            <div class="p-car-thumbnails">

                                <a class="car-hover" href="/product/{{ rs.id }}/{{ rs.slug }}/">
                                    <img src="{{ rs.image.url }}" alt="JSOFT" style="height: 160px">

                                </a>
                            </div>

                            <div class="p-car-content">
                                <h3>
                                    <span class="price"><i class="fa fa-tag"></i> {{ rs.price }}</span>
                                </h3>
                                <a href="/product/{{ rs.id }}/{{ rs.slug }}/">
                                    <h3 style="color:#000000"> {{ rs.title }}</h3>
                                </a>
                                <div class="p-car-feature">
                                    <p>{{ rs.detail |safe }}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Single Popular Car End -->
                {% endfor %}

            </div>
        </div>
    </div>
</div>

home/templates/faq.html
{% extends "homebase.html" %}
{% block title %} Sıkça Sorulan Sorular{% endblock %}
{% block keywords %} {{ setting.key }} {% endblock %}
{% block description %} {{ setting.description }}{% endblock %}
{% block head %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}">



{% endblock %}

{% block body %}
    {% load static %}

    <section id="about-area" class="section-padding">

        <div class="container" style="margin-top:140px">

            <div class="row">

                <div class="col-lg-9">
                    <div class="about-content">
                        <h3 style="margin: 20px 0px 10px 0px">Sıkça Sorulan Sorular</h3>
                        <div id="accordion">
                            {% for rs in faq %}
                                <h3>{{ rs.question }}</h3>
                                <div>
                                <p>{{ rs.answer }}</p>
                                </div>
                            {% endfor %}
                        </div>

                    </div>

                </div>

            </div>
        </div>
    </section>

{% endblock %}

home/templates/header.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<!-- jQuery UI !-->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

<header id="header-area" class="fixed-top">
    <!--== Header Top Start ==-->
    {% load static %}
    <div id="header-top" class="d-none d-xl-block">
        <div class="container">
            <div class="row">
                <!--== Single HeaderTop Start ==-->
                <div class="col-lg-3 text-left">
                    <i class="fa fa-map-marker"></i> {{ setting.address }}
                </div>
                <!--== Single HeaderTop End ==-->


                <!--== Social Icons Start ==-->
                <div class="col-lg-3 text-right">
                    <div class="header-social-icons">
                        <a href="{{ setting.github }}"><i class="fa fa-github"></i></a>
                        <a href="{{ setting.facebook }}"><i class="fa fa-facebook"></i></a>
                        <a href="{{ setting.linkedin }}"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
                <!--== Social Icons End ==-->
            </div>
        </div>
    </div>
    <!--== Header Top End ==-->

    <!--== Header Bottom Start ==-->
    <div id="header-bottom">
        <div class="container">
            <div class="row">
                <!--== Logo Start ==-->
                <div class="col-lg-2">
                    <a href="/" class="logo">
                        <img src="{% static 'img/logo.png' %}" alt="JSOFT">
                    </a>
                </div>
                <!--== Logo End ==-->

                <!--== Main Menu Start ==-->
                <div class="col-lg-10 d-none d-xl-block">
                    <nav class="mainmenu alignright">

                        <ul>
                            <li><a href="/">Anasayfa</a>

                            </li>
                            <li><a href="/hakkimizda">Hakkımızda</a></li>
                            <li><a href="/referanslar">Referanslar</a></li>
                            <li><a href="/iletisim">İletişim</a></li>
                            {% if user.id is not None %}
                                <li><a href="/user">Hesabım</a></li>
                                <li><a href="/logout">Logout</a></li>
                            {% else %}
                                <li><a href="/login">Login</a></li>
                            {% endif %}


                        </ul>


                    </nav>

                </div>
                <!--== Main Menu End ==-->
            </div>
        </div>
    </div>
    <!--== Header Bottom End ==-->
</header>

home/templates/order_form.html
{% extends "homebase.html" %}
{% block title %} Rezervasyon {% endblock %}
{% block keywords %} {{ setting.key }} {% endblock %}
{% block description %} {{ setting.description }}{% endblock %}
{% block head %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}">
{% endblock %}
{% block body %}
    {% load static %}
    <section id="about-area" class="section-padding" style="margin-top: 120px">

        <div class="container">

            <div class="row">
 <div class="col-lg-6">
                    <h3 style="margin: 20px 0px 10px 0px">DETAY</h3>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form action="" method="post">

                        {% csrf_token %} <!--  saldırılardan korur-->
                        <p><label for="id_first_name">Ad</label>
                            <input type="text" name="first_name" value="{{ user.first_name }}" class="name-input"
                                   maxlength="40"></p>
                        <p><label for="id_last_name">Soyad</label>
                            <input type="text" name="last_name" value="{{ user.last_name }}" class="name-input"
                                   maxlength="40"></p>
                        <p><label for="id_address">Adres</label>
                            <input type="text" name="address" value="{{ profile.address }}" class="name-input"
                                   maxlength="100"></p>
                        <p><label for="id_phone">Telefon</label>
                            <input type="text" name="phone" value="{{ profile.phone }}" class="name-input"
                                   maxlength="20"></p>
                        <p><label for="id_city">Şehir</label>
                            <select name="city" class="input-group" id="id_city">
                                <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                <option value="Istanbul">İstanbul</option>
                                <option value="Ankara">Ankara</option>
                                <option value="Kocaeli">Kocaeli</option>
                                <option value="Eskişehir">Eskişehir</option>
                                <option value="Karabük">Karabük</option>
                            </select>
                        <p><label for="id_country">Ülke</label>
                            <input type="text" name="country" value="{{ profile.county }}" class="name-input"
                                   maxlength="20" id="id_country"></p>
                            <!--
                            <input  name="date_start" value="{{ date_start }}">

                            <input   name="date_end" value="{{ date_end }}">

                            <input  name="quatity" value="{{ quatity }}"
                            >
                            <input   name="car_id" value="{{ car_id }}"
                            >-->
                               <button class="kirala">Kirala</button>
                    </div>
                    </form>
                <div class="col-lg-6">
                    <h3 style="margin: 20px 0px 10px 0px">Kart Bilgileri</h3>
                    <p><label for="id_total">Ücret:</label>
                        <input type="text" name="total" readonly value="{{ total }}" class="name-input">
                    <p><label for="id_firs_name">Kartın Üstündeki İsim</label>
                        <input type="text" name="number" value="" class="name-input" maxlength="16">
                    <p><label for="id_firs_name">Kart Numarası</label>
                        <input type="text" name="number" value="" class="name-input" maxlength="16">
                    <p><label for="id_firs_name">Ay/Yıl</label>
                        <input type="text" name="expdate" value="" class="name-input" placeholder="ay/yıl">
                    <p><label for="id_firs_name">CV2</label>
                        <input type="text" name="expdate" value="" class="name-input">
                </div>



            </div>
        </div>
        </div>
    </section>
{% endblock %}

home/templates/slider.html
<section id="home-slider-area">
    {% load static %}
    {% for rs in sliderdata %}
        <div class="home-slider-item slider-bg-1 overlay" style="background-image: url('{{ rs.image.url }}')">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="slideshowcontent">
                            <h1>{{ rs.title }}</h1>

                            <p>
                                <a href="/product/{{ rs.id }}/{{ rs.slug }}" style="color:white;">Kirala</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</section>